server:
  port: 8001
spring:
  application:
    name: jushi-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: jushi-web
          uri: lb://jushi-web
          predicates:
            - Path=/api/web/**
          filters:
            - StripPrefix=2
        - id: jushi-admin
          uri: lb://jushi-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
        - id: jushi-auth-server
          uri: lb://jushi-auth-server
          predicates:
            - Path=/api/uaa/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: '*'
#debug
#logging:
#  level:
#    root: debug